app = "birthday-timeline-tigris"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3001"
  NODE_ENV = "production"
  AWS_REGION = "auto"
  AWS_ENDPOINT_URL_S3 = "https://fly.storage.tigris.dev"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    restart_limit = 0
    timeout = "10s"
    path = "/health"
    method = "GET"

[processes]
  app = "npm start"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

# Deploy configuration
[deploy]
  release_command = "npm run build"
  strategy = "rolling"

# Volume for persistent data (if needed)
# [mounts]
#   source = "data"
#   destination = "/app/data"